import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./_components/theme-provider";
import { ReactNode } from "react";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { PaginationDemo } from "./_components/Pagination";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type RootLayoutProps = {
  children: ReactNode;
};
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <PaginationDemo />
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
